civilizaciones = {
    "egipcios": {
        "id": 1,
        "nombre": "egipcios",
        "origen": "Egipto",
        "ubicacion": "África",
        "año_inicio": -3150,
        "año_fin": 30,
        "imagen": "egipcios.jpg",
        "descripcion corta": "Los egipcios fueron una civilización antigua que se desarrolló en el noreste de África",
        "etnia": "Afroasiática",
        "idioma": "Egipcio antiguo",
        "religion": "Politeísta",
        "politica": "Monarquía",
        "sociedad": "Jerarquizada",
        "poblacion": "Alrededor de 3 millones de habitantes",
        "periodo": "Antigüedad",
        "calificacion": [
            {"name": "tecnologia", "value": 5},
            {"name": "arte", "value": 5},
            {"name": "ciencia", "value": 5},
            {"name": "historia", "value": 5},
            {"name": "matematicas", "value": 5},
            {"name": "arquitectura", "value": 5},
        ],
        "wars": [
            {"name": "Guerras médicas", "year": -499},
            {"name": "Guerras persas", "year": -499},
            {"name": "Guerras civiles", "year": -499},
            {"name": "Guerras romanas", "year": -499},
        ],
        "dioses": [
            {"name": "Ra", "description": "Dios del sol"},
            {"name": "Osiris", "description": "Dios de la muerte"},
            {"name": "Isis", "description": "Diosa de la maternidad"},
            {"name": "Horus", "description": "Dios del cielo"},
            {"name": "Anubis", "description": "Dios de los muertos"},
        ],
        "figuras": [
            {
                "name": "Cleopatra",
                "description": "Reina de Egipto",
                "image": "cleopatra.jpg",
                "year": -69,
            },
            {
                "name": "Tutankamón",
                "description": "Faraón de Egipto",
                "image": "tutankamon.jpg",
                "year": -1332,
            },
            {
                "name": "Ramsés II",
                "description": "Faraón de Egipto",
                "image": "ramses.jpg",
                "year": -1303,
            },
            {
                "name": "Nefertiti",
                "description": "Reina de Egipto",
                "image": "nefertiti.jpg",
                "year": -1370,
            },
            {
                "name": "Akenatón",
                "description": "Faraón de Egipto",
                "image": "akenaton.jpg",
                "year": -1386,
            },
            {
                "name": "Hatshepsut",
                "description": "Reina de Egipto",
                "image": "hatshepsut.jpg",
                "year": -1508,
            },
            {
                "name": "Imhotep",
                "description": "Arquitecto de Egipto",
                "image": "imhotep.jpg",
                "year": -2667,
            },
            {
                "name": "Ankhesenamón",
                "description": "Reina de Egipto",
                "image": "ankhesenamon.jpg",
                "year": -1348,
            },
            {
                "name": "Ptolomeo I",
                "description": "Faraón de Egipto",
                "image": "ptolomeo.jpg",
                "year": -367,
            },
            {
                "name": "Ptolomeo II",
                "description": "Faraón de Egipto",
                "image": "ptolomeo.jpg",
                "year": -283,
            },
            {
                "name": "Ptolomeo III",
                "description": "Faraón de Egipto",
                "image": "ptolomeo.jpg",
                "year": -246,
            },
            {
                "name": "Ptolomeo IV",
                "description": "Faraón de Egipto",
                "image": "ptolomeo.jpg",
                "year": -244,
            },
            {
                "name": "Ptolomeo V",
                "description": "Faraón de Egipto",
                "image": "ptolomeo.jpg",
                "year": -210,
            },
            {
                "name": "Ptolomeo VI",
                "description": "Faraón de Egipto",
                "image": "ptolomeo.jpg",
                "year": -186,
            },
            {
                "name": "Ptolomeo VII",
                "description": "Faraón de Egipto",
                "image": "ptolomeo.jpg",
                "year": -145,
            },
            {
                "name": "Ptolomeo VIII",
                "description": "Faraón de Egipto",
                "image": "ptolomeo.jpg",
                "year": -182,
            },
            {
                "name": "Ptolomeo IX",
                "description": "Faraón de Egipto",
                "image": "ptolomeo.jpg",
                "year": -143,
            },
            {
                "name": "Ptolomeo X",
                "description": "Faraón de Egipto",
                "image": "ptolomeo.jpg",
                "year": -118,
            },
            {
                "name": "Ptolomeo XI",
                "description": "Faraón de Egipto",
                "image": "ptolomeo.jpg",
                "year": -107,
            },
            {
                "name": "Ptolomeo XII",
                "description": "Faraón de Egipto",
                "image": "ptolomeo.jpg",
                "year": -100,
            },
            {
                "name": "Ptolomeo XIII",
                "description": "Faraón de Egipto",
                "image": "ptolomeo.jpg",
                "year": -62,
            },
            {
                "name": "Ptolomeo XIV",
                "description": "Faraón de Egipto",
                "image": "ptolomeo.jpg",
                "year": -59,
            },
            {
                "name": "Ptolomeo XV",
                "description": "Faraón de Egipto",
                "image": "ptolomeo.jpg",
                "year": -47,
            },
            {
                "name": "Ptolomeo XVI",
                "description": "Faraón de Egipto",
                "image": "ptolomeo.jpg",
                "year": -44,
            },
            {
                "name": "Ptolomeo XVII",
                "description": "Faraón de Egipto",
                "image": "ptolomeo.jpg",
                "year": -36,
            },
            {
                "name": "Ptolomeo XVIII",
                "description": "Faraón de Egipto",
                "image": "ptolomeo.jpg",
                "year": -33,
            },
            {
                "name": "Ptolomeo XIX",
                "description": "Faraón de Egipto",
                "image": "ptolomeo.jpg",
                "year": -29,
            },
        ],
        "periodos": [
            {"name": "Imperio Antiguo", "year": -2686},
            {"name": "Imperio Medio", "year": -2055},
            {"name": "Imperio Nuevo", "year": -1550},
            {"name": "Tercer Período Intermedio", "year": -1070},
            {"name": "Bajo Egipto", "year": -664},
            {"name": "Época Ptolemaica", "year": -332},
            {"name": "Época Romana", "year": 30},
        ],
        "descripcion_larga": "Los egipcios fueron una civilización antigua que se desarrolló en el noreste de África, en la región que hoy es Egipto. La civilización egipcia se desarrolló a lo largo de más de 3000 años, desde el año 3150 a.C. hasta el año 30 a.C. La civilización egipcia es conocida por sus grandes monumentos, como las pirámides y las esfinges, así como por su arte, arquitectura, religión y cultura.",
        "publicaciones": [
            {
                "titulo": "El libro de los muertos",
                "autor": "Anónimo",
                "año": -1550,
                "genero": "Religioso",
            },
            {
                "titulo": "Papiro de Ebers",
                "autor": "Anónimo",
                "año": -1550,
                "genero": "Científico",
            },
            {
                "titulo": "Papiro de Edwin Smith",
                "autor": "Anónimo",
                "año": -1550,
                "genero": "Científico",
            },
            {
                "titulo": "Papiro de Turín",
                "autor": "Anónimo",
                "año": -1550,
                "genero": "Histórico",
            },
            {
                "titulo": "Papiro de Harris",
                "autor": "Anónimo",
                "año": -1550,
                "genero": "Histórico",
            },
            {
                "titulo": "Papiro de Ipuwer",
                "autor": "Anónimo",
                "año": -1550,
                "genero": "Histórico",
            },
            {
                "titulo": "Papiro de Ani",
                "autor": "Anónimo",
                "año": -1550,
                "genero": "Religioso",
            },
            {
                "titulo": "Papiro de Kahum",
                "autor": "Anónimo",
                "año": -1550,
                "genero": "Religioso",
            },
            {
                "titulo": "Papiro de Hunefer",
                "autor": "Anónimo",
                "año": -1550,
                "genero": "Religioso",
            },
            {
                "titulo": "Papiro de Nu",
                "autor": "Anónimo",
                "año": -1550,
                "genero": "Religioso",
            },
            {
                "titulo": "Papiro de Ankhsheshonq",
                "autor": "Anónimo",
                "año": -1550,
                "genero": "Religioso",
            },
            {
                "titulo": "Papiro de Nany",
                "autor": "Anónimo",
                "año": -1550,
                "genero": "Religioso",
            },
            {
                "titulo": "Papiro de Nekht",
                "autor": "Anónimo",
                "año": -1550,
                "genero": "Religioso",
            },
            {
                "titulo": "Papiro de Nebseni",
                "autor": "Anónimo",
                "año": -1550,
                "genero": "Religioso",
            },
            {
                "titulo": "Papiro de Ani",
                "autor": "Anónimo",
                "año": -1550,
                "genero": "Religioso",
            },
            {
                "titulo": "Papiro de Nany",
                "autor": "Anónimo",
                "año": -1550,
                "genero": "Religioso",
            },
            {
                "titulo": "Papiro de Nekht",
                "autor": "Anónimo",
                "año": -1550,
                "genero": "Religioso",
            },
            {
                "titulo": "Papiro de Nebseni",
                "autor": "Anónimo",
                "año": -1550,
                "genero": "Religioso",
            },
        ],
        "logros": [
            "Construcción de las pirámides",
            "Desarrollo de la escritura jeroglífica",
            "Desarrollo de la astronomía",
            "Desarrollo de la medicina",
            "Desarrollo de la arquitectura",
        ],
    },
    "romanos": {
        "id": 2,
        "nombre": "romanos",
        "origen": "Roma",
        "ubicacion": "Europa",
        "año_inicio": -753,
        "año_fin": 476,
        "imagen": "romanos.jpg",
        "descripcion corta": "Los romanos fueron una civilización antigua que se desarrolló en la península itálica",
        "etnia": "Indoeuropea",
        "idioma": "Latín",
        "religion": "Politeísta",
        "politica": "República y Imperio",
        "sociedad": "Estratificada",
        "poblacion": "Alrededor de 50 millones de habitantes",
        "periodo": "Antigüedad",
        "calificacion": [
            {"name": "tecnologia", "value": 5},
            {"name": "arte", "value": 5},
            {"name": "ciencia", "value": 5},
            {"name": "historia", "value": 5},
            {"name": "matematicas", "value": 5},
            {"name": "arquitectura", "value": 5},
        ],
        "wars": [
            {"name": "Guerras púnicas", "year": -264},
            {"name": "Guerras civiles", "year": -133},
            {"name": "Guerras gálicas", "year": -58},
            {"name": "Guerras romano-persas", "year": 224},
        ],
        "dioses": [
            {"name": "Júpiter", "description": "Dios del cielo"},
            {"name": "Marte", "description": "Dios de la guerra"},
            {"name": "Venus", "description": "Diosa del amor"},
            {"name": "Mercurio", "description": "Dios del comercio"},
            {"name": "Neptuno", "description": "Dios del mar"},
        ],
        "figuras": [
            {
                "name": "Julio César",
                "description": "Dictador de Roma",
                "image": "julio_cesar.jpg",
                "year": -100,
            },
            {
                "name": "Augusto",
                "description": "Primer emperador de Roma",
                "image": "augusto.jpg",
                "year": -63,
            },
            {
                "name": "Cicerón",
                "description": "Orador y político romano",
                "image": "ciceron.jpg",
                "year": -106,
            },
            {
                "name": "Marco Antonio",
                "description": "General romano",
                "image": "marco_antonio.jpg",
                "year": -83,
            },
            {
                "name": "Cleopatra",
                "description": "Reina de Egipto",
                "image": "cleopatra.jpg",
                "year": -69,
            },
            {
                "name": "Nerón",
                "description": "Emperador de Roma",
                "image": "neron.jpg",
                "year": 37,
            },
            {
                "name": "Trajano",
                "description": "Emperador de Roma",
                "image": "trajano.jpg",
                "year": 53,
            },
            {
                "name": "Marco Aurelio",
                "description": "Emperador de Roma",
                "image": "marco_aurelio.jpg",
                "year": 121,
            },
            {
                "name": "Commodus",
                "description": "Emperador de Roma",
                "image": "commodus.jpg",
                "year": 161,
            },
            {
                "name": "Diocleciano",
                "description": "Emperador de Roma",
                "image": "diocleciano.jpg",
                "year": 244,
            },
            {
                "name": "Constantino",
                "description": "Emperador de Roma",
                "image": "constantino.jpg",
                "year": 272,
            },
            {
                "name": "Teodosio",
                "description": "Emperador de Roma",
                "image": "teodosio.jpg",
                "year": 347,
            },
            {
                "name": "Rómulo Augusto",
                "description": "Emperador de Roma",
                "image": "romulo_augusto.jpg",
                "year": 461,
            },
        ],
        "periodos": [
            {"name": "Monarquía", "year": -753},
            {"name": "República", "year": -509},
            {"name": "Imperio", "year": 27},
            {"name": "Bajo Imperio", "year": 284},
        ],
        "descripcion_larga": "Los romanos fueron una civilización antigua que se desarrolló en la península itálica, en la región que hoy es Italia. La civilización romana se desarrolló a lo largo de más de 1000 años, desde el año 753 a.C. hasta el año 476 d.C. La civilización romana es conocida por su arte, arquitectura, literatura, política, religión y cultura.",
        "publicaciones": [
            {
                "titulo": "La Eneida",
                "autor": "Virgilio",
                "año": -29,
                "genero": "Literario",
            },
            {
                "titulo": "Comentarios a la guerra de las Galias",
                "autor": "Julio César",
                "año": -58,
                "genero": "Histórico",
            },
            {
                "titulo": "Historia de Roma",
                "autor": "Tito Livio",
                "año": -9,
                "genero": "Histórico",
            },
            {
                "titulo": "Historia natural",
                "autor": "Plinio el Viejo",
                "año": 77,
                "genero": "Científico",
            },
            {
                "titulo": "Comentarios a la guerra civil",
                "autor": "César",
                "año": -58,
                "genero": "Histórico",
            },
            {
                "titulo": "Historia de Roma",
                "autor": "Tito Livio",
                "año": -9,
                "genero": "Histórico",
            },
            {
                "titulo": "Historia natural",
                "autor": "Plinio el Viejo",
                "año": 77,
                "genero": "Científico",
            },
            {
                "titulo": "Comentarios a la guerra civil",
                "autor": "César",
                "año": -58,
                "genero": "Histórico",
            },
        ],
        "logros": [
            "Construcción de acueductos",
            "Desarrollo de la arquitectura",
            "Desarrollo de la ingeniería",
            "Desarrollo de la literatura",
            "Desarrollo de la filosofía",
        ],
    },
    "griegos": {
        "id": 3,
        "nombre": "griegos",
        "origen": "Grecia",
        "ubicacion": "Europa",
        "año_inicio": -2700,
        "año_fin": 146,
        "imagen": "griegos.jpg",
        "descripcion corta": "Los griegos fueron una civilización antigua que se desarrolló en la península balcánica",
        "etnia": "Indoeuropea",
        "idioma": "Griego antiguo",
        "religion": "Politeísta",
        "politica": "Ciudades-Estado",
        "sociedad": "Estratificada",
        "poblacion": "Alrededor de 5 millones de habitantes",
        "periodo": "Antigüedad",
        "calificacion": [
            {"name": "tecnologia", "value": 5},
            {"name": "arte", "value": 5},
            {"name": "ciencia", "value": 5},
            {"name": "historia", "value": 5},
            {"name": "matematicas", "value": 5},
            {"name": "arquitectura", "value": 5},
        ],
        "wars": [
            {"name": "Guerras médicas", "year": -499},
            {"name": "Guerras del Peloponeso", "year": -431},
            {"name": "Guerras macedónicas", "year": -214},
            {"name": "Guerras romano-macedónicas", "year": 168},
        ],
        "dioses": [
            {"name": "Zeus", "description": "Dios del cielo"},
            {"name": "Atenea", "description": "Diosa de la sabiduría"},
            {"name": "Apolo", "description": "Dios del sol"},
            {"name": "Artemisa", "description": "Diosa de la caza"},
            {"name": "Afrodita", "description": "Diosa del amor"},
        ],
        "figuras": [
            {
                "name": "Homero",
                "description": "Poeta griego",
                "image": "homero.jpg",
                "year": -800,
            },
            {
                "name": "Sócrates",
                "description": "Filósofo griego",
                "image": "socrates.jpg",
                "year": -469,
            },
            {
                "name": "Platón",
                "description": "Filósofo griego",
                "image": "platon.jpg",
                "year": -427,
            },
            {
                "name": "Aristóteles",
                "description": "Filósofo griego",
                "image": "aristoteles.jpg",
                "year": -384,
            },
            {
                "name": "Alejandro Magno",
                "description": "Rey de Macedonia",
                "image": "alejandro_magno.jpg",
                "year": -356,
            },
            {
                "name": "Pericles",
                "description": "Político ateniense",
                "image": "pericles.jpg",
                "year": -495,
            },
            {
                "name": "Heródoto",
                "description": "Historiador griego",
                "image": "herodoto.jpg",
                "year": -484,
            },
            {
                "name": "Demóstenes",
                "description": "Orador ateniense",
                "image": "demostenes.jpg",
                "year": -384,
            },
            {
                "name": "Tucídides",
                "description": "Historiador ateniense",
                "image": "tucidides.jpg",
                "year": -460,
            },
            {
                "name": "Eurípides",
                "description": "Dramaturgo griego",
                "image": "euripides.jpg",
                "year": -480,
            },
            {
                "name": "Sófocles",
                "description": "Dramaturgo griego",
                "image": "sofocles.jpg",
                "year": -496,
            },
            {
                "name": "Aristófanes",
                "description": "Dramaturgo griego",
                "image": "aristofanes.jpg",
                "year": -446,
            },
            {
                "name": "Píndaro",
                "description": "Poeta griego",
                "image": "pindaro.jpg",
                "year": -518,
            },
            {
                "name": "Esquilo",
                "description": "Dramaturgo griego",
                "image": "esquilo.jpg",
                "year": -525,
            },
            {
                "name": "Hesíodo",
                "description": "Poeta griego",
                "image": "hesiodo.jpg",
                "year": -700,
            },
            {
                "name": "Anacreonte",
                "description": "Poeta griego",
                "image": "anacreonte.jpg",
                "year": -570,
            },
            {
                "name": "Safo",
                "description": "Poeta griega",
                "image": "safo.jpg",
                "year": -630,
            },
            {
                "name": "Píndaro",
                "description": "Poeta griego",
                "image": "pindaro.jpg",
                "year": -518,
            },
            {
                "name": "Esquilo",
                "description": "Dramaturgo griego",
                "image": "esquilo.jpg",
                "year": -525,
            },
            {
                "name": "Hesíodo",
                "description": "Poeta griego",
                "image": "hesiodo.jpg",
                "year": -700,
            },
            {
                "name": "Anacreonte",
                "description": "Poeta griego",
                "image": "anacreonte.jpg",
                "year": -570,
            },
            {
                "name": "Safo",
                "description": "Poeta griega",
                "image": "safo.jpg",
                "year": -630,
            },
        ],
        "periodos": [
            {"name": "Cultura cicládica", "year": -3200},
            {"name": "Cultura minoica", "year": -2600},
            {"name": "Cultura micénica", "year": -1600},
            {"name": "Época arcaica", "year": -800},
            {"name": "Época clásica", "year": -500},
            {"name": "Época helenística", "year": -323},
        ],
        "descripcion_larga": "Los griegos fueron una civilización antigua que se desarrolló en la península balcánica, en la región que hoy es Grecia. La civilización griega se desarrolló a lo largo de más de 3000 años, desde el año 2700 a.C. hasta el año 146 a.C. La civilización griega es conocida por su arte, arquitectura, literatura, política, religión y cultura.",
        "publicaciones": [
            {
                "titulo": "La Ilíada",
                "autor": "Homero",
                "año": -800,
                "genero": "Literario",
            },
            {
                "titulo": "La Odisea",
                "autor": "Homero",
                "año": -800,
                "genero": "Literario",
            },
            {
                "titulo": "Historia de las Guerras del Peloponeso",
                "autor": "Tucídides",
                "año": -460,
                "genero": "Histórico",
            },
            {
                "titulo": "Historia de la Guerra del Peloponeso",
                "autor": "Tucídides",
                "año": -460,
                "genero": "Histórico",
            },
            {
                "titulo": "Historia de Grecia",
                "autor": "Heródoto",
                "año": -484,
                "genero": "Histórico",
            },
            {
                "titulo": "Historia de Grecia",
                "autor": "Heródoto",
                "año": -484,
                "genero": "Histórico",
            },
            {
                "titulo": "Historia de Grecia",
                "autor": "Heródoto",
                "año": -484,
                "genero": "Histórico",
            },
            {
                "titulo": "Historia de Grecia",
                "autor": "Heródoto",
                "año": -484,
                "genero": "Histórico",
            },
        ],
        "logros": [
            "Desarrollo de la democracia",
            "Desarrollo de la filosofía",
            "Desarrollo de la literatura",
            "Desarrollo de la arquitectura",
            "Desarrollo de la ciencia",
        ],
    },
}
