"""init 2.0

Revision ID: 2e2ba75a385a
Revises: 1e8eb2c9a31b
Create Date: 2024-05-26 21:50:11.752707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e2ba75a385a'
down_revision = '1e8eb2c9a31b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('civilization_achievement', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('civilizationAchievement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('civilization_id', sa.Integer(), nullable=True),
    sa.Column('achievement_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievement.id'], ),
    sa.ForeignKeyConstraint(['civilization_id'], ['civilization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('civilization', sa.Column('name', sa.String(), nullable=True))
    op.add_column('civilization', sa.Column('origin', sa.String(), nullable=True))
    op.add_column('civilization', sa.Column('initYear', sa.Integer(), nullable=True))
    op.add_column('civilization', sa.Column('endYear', sa.Integer(), nullable=True))
    op.add_column('civilization', sa.Column('description', sa.String(), nullable=True))
    op.add_column('civilization', sa.Column('achievements_civilizations', sa.String(), nullable=True))
    op.drop_column('civilization', 'nombre')
    op.drop_column('civilization', 'descripcion')
    op.drop_column('civilization', 'logros')
    op.drop_column('civilization', 'año_inicio')
    op.drop_column('civilization', 'origen')
    op.drop_column('civilization', 'año_fin')
    op.add_column('image', sa.Column('continent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'image', 'continent', ['continent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'image', type_='foreignkey')
    op.drop_column('image', 'continent_id')
    op.add_column('civilization', sa.Column('año_fin', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('civilization', sa.Column('origen', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('civilization', sa.Column('año_inicio', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('civilization', sa.Column('logros', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('civilization', sa.Column('descripcion', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('civilization', sa.Column('nombre', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('civilization', 'achievements_civilizations')
    op.drop_column('civilization', 'description')
    op.drop_column('civilization', 'endYear')
    op.drop_column('civilization', 'initYear')
    op.drop_column('civilization', 'origin')
    op.drop_column('civilization', 'name')
    op.drop_table('civilizationAchievement')
    op.drop_table('achievement')
    # ### end Alembic commands ###
